kind: ConfigMap
apiVersion: v1
metadata:
  name: customer-config-map
  namespace: default
data:
  db-username : "spring"
  db-password : "springspring"
  db-endpoint : "jdbc:mysql://spring.cno8yecwarzn.us-east-1.rds.amazonaws.com:3306/springdb"


