apiVersion: v1
kind: Secret
metadata:
  name: customer-secrets
type: Opaque
data:
  db-username: c3ByaW5n
  db-password: c3ByaW5nc3ByaW5n
  db-root-password: c3ByaW5nc3ByaW5nc3ByaW5n
  # db-endpoint: amRiYzpteXNxbDovL3NwcmluZy5jbm84eWVjd2Fyem4udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjMzMDYvc3ByaW5nZGI=







