#To grant full access to Kubernetes pods to Naveen and no access to pods in Kubernetes to Komal using Role-Based Access Control (RBAC), you can achieve this by creating specific roles and role bindings in Kubernetes

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: no-pod-access-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: []  # No verbs granted
