apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: no-pod-access-binding
subjects:
- kind: User
  name: komal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: no-pod-access-cluster-role
  apiGroup: rbac.authorization.k8s.io
