apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Change this if your pods are in a different namespace
  name: pod-access-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]  # Adjust verbs as per your requirements
