apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: default  # Change this if your pods are in a different namespace
subjects:
- kind: User
  name: naveen
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io
