apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: naveen

[root@ip-172-31-86-45 customer]# cat role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: naveen  # Replace 'your-namespace' with your desired namespace
  name: my-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]