apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: packersmovers
    tier: backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: packersmovers
      tier: backend
  template:
    metadata:
      labels:
        app: packersmovers
        tier: backend
    spec:
      containers:
      - name: customer
        image: 637423236688.dkr.ecr.us-east-1.amazonaws.com/spring:latest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-secrets
              key: db-password
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: customer-secrets
              key: db-endpoint
        ports:
        - containerPort: 8081

----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: packersmovers
    tier: backend
